config/routes.rb
Rails.application.routes.draw do
  resources :galleries, excpet: [:show]
  get 'gallery/:id', to: 'galleries#show', as: 'gallery_show'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use: :slugged
  
    validates_presence_of :title, :body

    belongs_to :topic
  end

app/models/gallery.rb
class Gallery < ApplicationRecord
    validates_presence_of :title, :body, :main_image, :thumb_image

    def self.angular
        where(subtitle: 'Angular')
    end
    
    scope :ruby_on_rails_gallery_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/models/skill.rb
class Skill < ApplicationRecord
    validates_presence_of :title, :percent_utilized
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates_presence_of :title

    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post was removed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
        
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
    def index
        @gallery_items = Gallery.all 
    end

    def angular
        @angular_gallery_items = Gallery.angular 
    end

    def new
        @gallery_item = Gallery.new
    end

    # POST /galleries
def create
    @gallery = Gallery.new(params.require(:gallery).permit(:title, :subtitle, :body))

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to galleries_path, notice: "gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @gallery_item = Gallery.find(params[:id])
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    @gallery_item = Gallery.find(params[:id])
    
    respond_to do |format|
      if @gallery_item.update(params.require(:gallery).permit(:title, :subtitle, :body))
        format.html { redirect_to galleries_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @gallery_item = Gallery.find(params[:id])
  end

  def destroy
    # Perform the lookup
    @gallery_item = Gallery.find(params[:id])

    # Destroy/delete the record
    @gallery_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Record was removed.' }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Blog Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/galleries/angular.html.erb
<h1>Angular Gallery Items</h1>

<%= link_to "Create New Item", new_gallery_url %>
<% @angular_gallery_items.each do |gallery_item| %>
  <p><%= link_to gallery_item.title, gallery_show_path(gallery_item) %></p>
  <p><%= gallery_item.subtitle %></p>
  <p><%= gallery_item.body %></p>
  <%= image_tag gallery_item.thumb_image unless gallery_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_gallery_path(gallery_item) %>
  <%= link_to 'Delete Gallery Item', gallery_path(gallery_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/galleries/edit.html.erb
<h1>Edit this Gallery Item</h1>

<%= form_for(@gallery_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/index.html.erb
<h1>Gallery</h1>

<%= link_to "Create New Item", new_gallery_url %>

<% @gallery_items.each do |gallery_item| %>
    <p><%= link_to gallery_item.title, gallery_show_path(gallery_item) %></p>
    <p><%= gallery_item.subtitle %></p>
    <p><%= gallery_item.body %></p>
    <%= image_tag gallery_item.thumb_image unless gallery_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_gallery_path(gallery_item.id) %>
    <%= link_to 'Delete Gallery Item', gallery_path(gallery_item), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/galleries/new.html.erb
<h1>Create a new Gallery Item</h1>

<%= form_for(@gallery_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/show.html.erb
<%= image_tag @gallery_item.main_image %>

<h1><%= @gallery_item.title %></h1>

<em><%= @gallery_item.subtitle %></em>

<p><%= @gallery_item.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Homepage</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>